[package]
name = "wm"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]

[dependencies]
regex = "0.1"
rustc-serialize = "0.3"
clap = "~2.19.*"
notify-rust = "3.*"



[[bin]]
name = "rspwm"
path = "src/main.rs"

[[bin]]
name = "rspc"
path = "src/client.rs"
